# Generated by Django 5.1.4 on 2025-01-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_songlike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
