# Generated by Django 5.1.4 on 2025-01-21 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_user_date_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='trendingsongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trendingsongs', to='music.post')),
            ],
        ),
    ]
