# Generated by Django 5.1.4 on 2025-01-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_trendingsongs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='email',
        ),
    ]
